[package]
name = "yrs-table-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
yrs = { version = "0.21", features = ["sync"] }
csv = "1.3.0"
fastrand = "2.1.1"
serde = { version = "1.0", features = ["derive"] }
zstd = "0.13.2"